/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedPanelRouteImport } from './routes/_authenticated/panel'

const AuthenticatedPanelRoute = AuthenticatedPanelRouteImport.update({
  id: '/_authenticated/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/panel': typeof AuthenticatedPanelRoute
}
export interface FileRoutesByTo {
  '/panel': typeof AuthenticatedPanelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/panel': typeof AuthenticatedPanelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/panel'
  fileRoutesByTo: FileRoutesByTo
  to: '/panel'
  id: '__root__' | '/_authenticated/panel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedPanelRoute: typeof AuthenticatedPanelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/panel': {
      id: '/_authenticated/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof AuthenticatedPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedPanelRoute: AuthenticatedPanelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
